### ISSUE TITLE
Reverse the arguments

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/repeating#6]
In reality the 99% use-case is an empty string, so makes sense to put the number first.

-

I don't want to do this right now as so much depends on it and I'd rather wait some months when I can require Node.js 4 without causing too many problems for users. Also drop the `is-finite` dependency then.

**Comment by SamVerschueren** [comment]
Why can we drop `is-finite`? Does ES2015 has a method for that?

**Comment by sindresorhus** [comment]
Yes, see the readme https://github.com/sindresorhus/is-finite It's just a ponyfill.

**Comment by SamVerschueren** [comment]
Cool :)
