### ISSUE TITLE
Theft of the codez!

### ISSUE THREAD

**Issue by RealDolos** [sindresorhus/repeating#8]
I was brought to my attention that you are a stealer of the codez, as reported in https://github.com/jonschlinkert/pad-left/issues/9#issuecomment-249396644

![repeating code stealings](https://cloud.githubusercontent.com/assets/9981466/19962389/a7c15d0c-a1b7-11e6-97db-7bfb96f5ac9c.png)

Please stop! :smile_cat:

**Comment by SamVerschueren** [comment]
I did my best but couldn't find much similarities to the implementation of [repeating](https://github.com/sindresorhus/repeating/blob/master/index.js) and [pad-left](https://github.com/jonschlinkert/pad-left/blob/master/index.js) or it's underlying module [repeat-string](https://github.com/jonschlinkert/repeat-string/blob/master/index.js).

**Comment by sindresorhus** [comment]
Jon is a troll and I didn't steal any of his code.

`repeat-string` first commit: https://github.com/jonschlinkert/repeat-string/commit/2831d54fc75ed5981bf94f28d412e1ed6be2fad3#diff-168726dbe96b3ce427e7fedce31bb0bcR1

`repeating` first commit: https://github.com/sindresorhus/repeating/commit/504be30b5d684bd724aa1a032d0108ee1ad83657#diff-168726dbe96b3ce427e7fedce31bb0bcR5
